"use client";
import { useState } from "react"; import { Check, LoaderCircle } from "lucide-react";
type RankId="donador"|"donador_plus"|"donador_premium";
type PublicRank={id:RankId;name:string;priceCents:number;durationDays:number;benefits:string[]};
const usernameRe=/^(?:[A-Za-z0-9_]{3,16}|\.[A-Za-z0-9_ ]{1,16})$/;
export function RankStore({ranks}:{ranks:PublicRank[]}){const [username,setUsername]=useState("");const [loading,setLoading]=useState<RankId|null>(null);const [error,setError]=useState("");
 async function checkout(rankId:RankId){if(!usernameRe.test(username)){setError("Usa tu username Java o el username Bedrock con prefijo .");return}setError("");setLoading(rankId);try{const r=await fetch("/api/checkout/tebex",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rankId,username})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo abrir Tebex");window.location.assign(d.redirectUrl)}catch(e){setError(e instanceof Error?e.message:"Error inesperado");setLoading(null)}}
 return <section id="rangos" className="mx-auto max-w-6xl px-6 py-24"><div className="mx-auto mb-14 max-w-2xl text-center [text-shadow:0_2px_8px_#000]"><p className="text-xs font-black uppercase tracking-[.25em] text-[#49c8ff]">Tienda del servidor</p><h2 className="mt-4 text-4xl font-black uppercase tracking-tight md:text-5xl">Elige tu rango cosmético</h2><p className="mt-4 text-slate-300">Cada rango dura 30 días y ayuda directamente con el hosting. Cero pay-to-win.</p></div>
 <div className="mx-auto mb-10 max-w-md"><label htmlFor="username" className="mb-2 block text-sm font-medium">Tu usuario de Minecraft <span className="text-cyan-400">*</span></label><input id="username" required maxLength={17} value={username} onChange={e=>{setUsername(e.target.value);setError("")}} placeholder="Steve_123 o .Bedrock" aria-describedby="user-help" className={`w-full rounded-xl border bg-white/[.04] px-4 py-3 outline-none placeholder:text-slate-700 focus:border-cyan-400/70 ${error?"border-red-400/70":"border-white/10"}`}/><p id="user-help" className={`mt-2 text-xs ${error?"text-red-300":"text-slate-600"}`}>{error||"Java: 3–16 caracteres. Bedrock: escribe también el prefijo ."}</p></div>
 <div className="grid gap-6 lg:grid-cols-3">{ranks.map((r,i)=><article key={r.id} className={`card-glow relative flex flex-col border-4 p-6 transition ${i===1?"border-[#39bfff] bg-[#0c2036]":"border-[#263d58] bg-[#0a1422]"}`}>{i===1&&<span className="absolute -top-4 right-5 border-2 border-[#8ae1ff] bg-[#167fbd] px-3 py-1 text-[10px] font-black uppercase tracking-wider text-white">Más elegido</span>}<div className="mb-5 grid h-14 w-14 place-items-center border-4 border-[#315577] bg-[#102843] text-2xl">{i===0?"⛏":i===1?"💎":"👑"}</div><p className="text-sm font-black uppercase tracking-widest text-[#73d5ff]">{r.name}</p><p className="mt-4 text-4xl font-black">${(r.priceCents/100).toFixed(0)} <small className="text-sm font-normal text-slate-500">USD / {r.durationDays} días</small></p><div className="my-6 h-1 bg-[#1b3048]"/><ul className="flex-1 space-y-3">{r.benefits.map(b=><li key={b} className="flex gap-3 text-sm text-slate-400"><Check className="h-4 w-4 shrink-0 text-[#49c8ff]"/>{b}</li>)}</ul><button disabled={!!loading} onClick={()=>checkout(r.id)} className={`mt-8 flex h-12 items-center justify-center font-black uppercase tracking-wide disabled:opacity-50 ${i===1?"pixel-button text-white":"border-3 border-[#38536f] bg-[#15273c] hover:bg-[#203a56]"}`}>{loading===r.id?<LoaderCircle className="h-5 w-5 animate-spin"/>:`Elegir ${r.name}`}</button></article>)}</div>
 <p className="mt-8 text-center text-xs text-slate-600">Pago seguro procesado por Tebex</p></section>}
