"use client";
import Image from "next/image";
import { useState } from "react"; import { Check, LoaderCircle } from "lucide-react";
type RankId="donador"|"donador_plus"|"donador_premium";
type PublicRank={id:RankId;name:string;priceCents:number;durationDays:number;benefits:string[]};
const usernameRe=/^(?:[A-Za-z0-9_]{3,16}|\.[A-Za-z0-9_ ]{1,16})$/;
const rankLogos:Record<RankId,{src:string;alt:string}>={
 donador:{src:"/bossly_logo_transparente.png",alt:"Emblema del rango Bossly"},
 donador_plus:{src:"/bossly_plus_logo_transparente.png",alt:"Emblema del rango Bossly Plus"},
 donador_premium:{src:"/bossly_premium_logo_transparente.png",alt:"Emblema del rango Bossly Premium"},
};
export function RankStore({ranks}:{ranks:PublicRank[]}){const [username,setUsername]=useState("");const [loading,setLoading]=useState<RankId|null>(null);const [error,setError]=useState("");
 async function checkout(rankId:RankId){if(!usernameRe.test(username)){setError("Usa tu username Java o el username Bedrock con prefijo .");return}setError("");setLoading(rankId);try{const r=await fetch("/api/checkout/tebex",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rankId,username})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo abrir Tebex");window.location.assign(d.redirectUrl)}catch(e){setError(e instanceof Error?e.message:"Error inesperado");setLoading(null)}}
 return <section id="rangos" className="rank-section mx-auto max-w-6xl px-6 py-24"><div className="mx-auto mb-14 max-w-2xl text-center [text-shadow:0_2px_8px_#000]"><p className="minecraft-heading text-xs font-black uppercase tracking-[.25em] text-cyan-200">Tienda del servidor</p><h2 className="minecraft-heading mt-4 text-4xl font-black uppercase tracking-tight md:text-5xl">Elige tu rango cosmético</h2><p className="mt-4 text-slate-300">Cada rango dura 30 días y ayuda directamente con el hosting. Cero pay-to-win.</p></div>
 <div className="username-panel pixel-panel mx-auto mb-12 max-w-md p-5"><label htmlFor="username" className="minecraft-heading mb-3 block text-sm">Tu usuario de Minecraft <span className="text-cyan-200">*</span></label><input id="username" required maxLength={17} value={username} onChange={e=>{setUsername(e.target.value);setError("")}} placeholder="Steve_123 o .Bedrock" aria-describedby="user-help" className={`w-full border-2 px-4 py-3 outline-none placeholder:text-slate-600 ${error?"border-red-300":"border-violet-300/50"}`}/><p id="user-help" className={`mt-2 text-xs ${error?"text-red-200":"text-slate-400"}`}>{error||"Java: 3–16 caracteres. Bedrock: escribe también el prefijo ."}</p></div>
 <div className="grid gap-7 lg:grid-cols-3">{ranks.map((r,i)=><article key={r.id} className={`rank-card rank-card-${r.id} card-glow relative flex flex-col border-4 p-6 transition`}>{i===1&&<span className="popular-badge minecraft-heading absolute -top-4 right-5 z-10 border-2 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-white">Más elegido</span>}<div className="rank-emblem mb-5 flex h-52 items-center justify-center overflow-hidden"><Image src={rankLogos[r.id].src} alt={rankLogos[r.id].alt} width={260} height={260} sizes="(max-width: 1024px) 260px, 22vw" className="h-full w-full object-contain drop-shadow-[0_12px_18px_rgba(0,0,0,.65)]"/></div><p className="rank-name minecraft-heading text-sm font-black uppercase tracking-widest">{r.name}</p><p className="rank-price minecraft-heading mt-4 text-4xl font-black">${(r.priceCents/100).toFixed(0)} <small className="text-xs font-normal text-slate-300">USD / {r.durationDays} días</small></p><div className="rank-divider my-6 h-1"/><ul className="flex-1 space-y-3">{r.benefits.map(b=><li key={b} className="flex gap-3 text-sm text-slate-300"><Check className="rank-check h-4 w-4 shrink-0"/>{b}</li>)}</ul><button disabled={!!loading} onClick={()=>checkout(r.id)} className="rank-button pixel-button mt-8 flex h-12 items-center justify-center font-black uppercase tracking-wide text-white disabled:opacity-50">{loading===r.id?<LoaderCircle className="h-5 w-5 animate-spin"/>:`Elegir ${r.name}`}</button></article>)}</div>
 <p className="mt-8 text-center text-xs text-slate-600">Pago seguro procesado por Tebex</p></section>}
